# fly.toml app configuration file generated for bero-events-worker on 2023-10-30T02:46:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bero-events-worker"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
